@LCB.Api_HostAddress = https://localhost:7274

### Login com Sucesso
POST {{ LCB.Api_HostAddress }}/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "teste@teste.com",
    "password": "1234"
}

### Login com Erro
POST {{ LCB.Api_HostAddress }}/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "teste1@teste.com",
    "password": "1234"
}

### Documentação Swagger
GET {{ LCB.Api_HostAddress }}/swagger/v1/swagger.json

### Ingest TikTok message (entra na fila)
POST {{ LCB.Api_HostAddress }}/messages/ingest
Content-Type: application/json

{
	"provider": 0,
	"author": "testUser",
	"text": "!fila",
	"timestamp": "2026-04-06 14:00:00"
}
