<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RunSettingsFilePath>coverlet.runsettings</RunSettingsFilePath>
        <VSTestCollect>XPlat Code Coverage</VSTestCollect>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\LCB.Domain\LCB.Domain.csproj" />
        <ProjectReference Include="..\..\src\LCB.Application\LCB.Application.csproj" />
        <ProjectReference Include="..\..\src\LCB.Infrastructure\LCB.Infrastructure.csproj" />
    </ItemGroup>
</Project>
