<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RunSettingsFilePath>coverlet.runsettings</RunSettingsFilePath>
        <VSTestCollect>XPlat Code Coverage</VSTestCollect>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" PrivateAssets="all" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Moq" />
        <PackageReference Include="TikTokLive_Sharp" />
        <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
        <PackageReference Include="xunit" />

        <ProjectReference Include="..\..\src\LCB.Application\LCB.Application.csproj" />
        <ProjectReference Include="..\..\src\LCB.Infrastructure\LCB.Infrastructure.csproj" />
    </ItemGroup>
</Project>
